### ISSUE TITLE
PRINTF EXISTE

### ISSUE THREAD

**Issue by n4rfy** [KB1te/syscall99#1]
USA A CACETA DO PRINTF MACACO MACACO MACACOOOOOO MACACO MACAOOOOOOOOM ACACO UGAUGA UGAU HGUA HUGHUHUHUHUH

**Comment by KB1te** [comment]
Please fix the code and try to not be racist.

**Comment by n4rfy** [comment]
> 
> 
> Please fix the code and try to not be racist.

DURRRRRRRRRRRRRR que UO 🤪
